project_id = "hesnceozbedzrgvylqrm"

[functions.generate-video]
verify_jwt = false

[functions.generate-smartflow]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.manage-api-keys]
verify_jwt = false

[functions.clone-voice]
verify_jwt = false

[functions.delete-voice]
verify_jwt = false
